#Required, this is how data is stored
storage:
  # mysql or sqlite
  type: mysql

# Economy provider to use: ozanarchy-economy or vault
economy-plugin: ozanarchy-economy

mysql:
  host: localhost
  port: 3306
  database: minecraft
  username: root
  password: password

sqlite:
  file: towns.db

# Enables or Disables /tm (Town Messages) & allows for setting of playername color for town chat
townmessages: true
townusercolor: "&e"

# Displays boss bar on entering/leaving towns
bossbar:
  town:
    color: GREEN
    style: SOLID
  wilderness:
    color: WHITE
    style: SOLID
  raid:
    color: RED
    style: SEGMENTED_10

# Spawn reminder settings
spawn-reminder:
  max-age-minutes: 60
  reminder-interval-minutes: 5

# Command to run when a town spawn is set. {player} will be replaced with the mayor's name.
# {world}, {x}, {y}, {z} will be replaced with the town's spawn location.
town-creation-command: "chestlock lock {world} {x} {y} {z} {player}"

# Delay in seconds for the /town spawn command
spawn-delay: 15

# Enables/disables town raiding via lockpicking town Lodestones.
raiding-allowed: true

# Upkeep settings
upkeep:
  # Delete town after this many minutes of unpaid upkeep past the normal upkeep interval.
  unpaid-delete-after-minutes: 1440

# Cache settings How often should the database be loaded into cache
cache:
  ttl-seconds: 15

#town costs and upkeep. Cost is the amount of money it costs to create a town. Base upkeep is the amount of money a town has to pay every upkeep period. Added member upkeep is the amount of money a town has to pay for each member added to the town. Added claim upkeep is the amount of money a town has to pay for each claim added to the town.
towns:
  createcost: 50.0
  claimcost: 5.0
  addedmemberupkeep: 5.0
  refundedmemberupkeep: 2.5
  addedclaimupkeep: 10.0
  refundedclaimupkeep: 5.0
  setspawntimer: 120

#Set worlds that you cant claim chunks in
unclaimable-worlds:
  - "world_nether"
  - "world_the_end"

#Chunk Partical Vizualiser
visualizer:
  enabled: true
  duration: 30
  own: SOUL_FIRE_FLAME
  enemy: FLAME
  wild: COMPOSTER

# List of blacklisted town names. Towns with these names cannot be created.
blacklisted-names:
  - "admin"
  - "server"
  - "console"
  - "nigger"
  - "nigga"
  - "n1gger"
  - "n1gga"
  - "owner"
  - "moderator"
  - "helper"
  - "staff"
  - "builder"
  - "nigg4"
  - "niga"
  - "nigg3r"
  - "n1gg3r"

# Messages, prefix, and help menus in messages.yml
